language: python
python: "3.6"

os:
 - linux

before_install:
   - sudo apt-get update
   - sudo apt-get install gzip
   - sudo ln -s /bin/tar /bin/gtar # this is because devtools requires gtar which I think is just an alias for 'tar'

install:
   - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
   - bash miniconda.sh -b - p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - hash -r
   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   - conda info -a
   - conda config --add channels defaults
   - conda config --add channels r
   - conda config --add channels conda-forge
   - conda config --add channels bioconda
   - conda create -q -n test-environment snakemake r r-devtools perl-app-cpanminus python=$TRAVIS_PYTHON_VERSION

script:
   - source activate test-environment
   - conda install -c r r-testthat
   - cpanm Bio::Perl
   - cpanm Statistics::Lite
   - sed -i 's/ENA/SRAtoolkit/' Snakefile
   - Rscript -e 'devtools::install_github("TBradley27/filtar_R")'
   - snakemake --version
   - snakemake --use-conda -p results/targets/no_reannotation/mmu/oocyte_chrY.contextpp.filt.tsv # no conservation mode
   - head results/targets/no_reannotation/mmu/oocyte_chrY.contextpp.filt.tsv
   - snakemake --use-conda -p results/targets/miRanda/mmu/oocyte/chrY_nr.filt.tsv # test miRanda
   - head results/targets/miRanda/mmu/oocyte/chrY_nr.filt.tsv
   - sed -i "s/no_conservation/with_conservation/" Snakefile
   - touch results/bed/no_reannotation/mmu_3UTR.chrY.filtered.bed # in order to retrigger target build
   - snakemake results/targets/no_reannotation/mmu/oocyte_chrY.contextpp.filt.tsv -n
   - snakemake --use-conda -p results/targets/no_reannotation/mmu/oocyte_chrY.contextpp.filt.tsv
   - head results/targets/no_reannotation/mmu/oocyte_chrY.contextpp.filt.tsv
   - Rscript -e 'testthat::test_file("targetscan_test.R")'
