language: python
python: "3.6"

install:
   - sudo apt-get update
   - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
   - bash miniconda.sh -b - p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - hash -r
   - conda config --set always_yes yes --set changeps1 no
   - conda update -q conda
   - conda info -a
   - conda config --add channels defaults
   - conda config --add channels conda-forge
   - conda config --add channels bioconda
   - conda create -q -n test-environment snakemake python=$TRAVIS_PYTHON_VERSION

script:
   - source activate test-environment
   - snakemake --version 
   - snakemake -n results/targets/mmu_liver_msa.contextpp.tsv
