tissues:
        mmu: 
                name_of_tissue: [] # insert relevant sample accessions here
        hsa:
                name_of_tissue: [] # insert relevant sample accessions here
samples:
         name_of_sample: [] # insert relevant run accessions here per sample

# e.g.
#
#
# tissues:
#       hsa:
#               kidney: [SRS00001]
#
# samples:
#               SRS00001: [SRR000001, SRR0000002]
