tissues:
        mmu: 
                name_of_tissue: [] # insert relevant sample accessions here
        hsa:
                adipose: [ERS025098] # insert relevant sample accessions here
samples:
         ERS025098: [ERR030880, ERR030888] # insert relevant run accessions here per sample

# e.g.
#
#
# tissues:
#       hsa:
#               kidney: [SRS00001]
#
# samples:
#               SRS00001: [SRR000001, SRR0000002]
