tissues:
        mmu: 
                liver: [SRS387309] # insert relevant sample accessions here
                retina: [SRS21256x]
                oocyte: [SRS540320]
        hsa:
samples:
         SRS387309: [SRR652248,SRR652249]
         SRS21256x: [SRR290901,SRR290902]
         SRS540320: [SRR1137901,SRR1137902]

single_end: [SRR652248,SRR652249,SRR1137901,SRR1137902]
paired_end: [SRR290901,SRR290902]

mouse:
        runs: [SRR652248,SRR652249,SRR290901,SRR290902,SRR1137901,SRR1137902]
human:
        runs: []

mirnas: [mmu-miR-29b-3p,mmu-miR-132-3p, mmu-miR-7061-5p] #if this configuration is left blank - processing is performed for all miRNAs of a given species as default
transcripts: [ENSMUST00000055032.13]
