tissues:
        mmu: 
                liver: [SRS387309] # insert relevant sample accessions here
                retina: [SRS21256x]
                oocyte: [SRS540320]
        hsa:
        dre:
                heart: [SRS566618]
        cel:
                zygote: [SRS1665604]   

samples:
         SRS387309: [SRR652248,SRR652249]
         SRS21256x: [SRR290901,SRR290902]
         SRS540320: [SRR1137901,SRR1137902]
         SRS566618: [SRR1554475]
         SRS1665604: [SRR4119904,SRR4119905]       

single_end: [SRR652248,SRR652249,SRR1137901,SRR1137902,SRR1554475]
paired_end: [SRR290901,SRR290902,SRR4119904,SRR4119905]

mirnas: [mmu-miR-188-5p] #if this configuration is left blank - processing is performed for all miRNAs of a given species as default
transcripts: [ENSMUST00000189888.6]
