tissues:
        hsa:
                HeLa: [SRR103287X]

samples:
        SRR103287X: [SRR1032877,SRR1032878]

mouse:
        runs: []
human:
        runs: [SRR1032875,SRR1032876,SRR1032877,SRR1032878]
        
single_end: [SRR1032875,SRR1032876,SRR1032877,SRR1032878]
paired_end: []

mirnas: [hsa-miR-155-5p] #if this configuration is left blank - processing is performed for all miRNAs of a given species as default
transcripts: []

sequence_data_source: ENA
