tissues:
        mmu: 
                liver: [SRS387309,foo] # insert relevant sample accessions here
        hsa:
samples:
         SRS387309: [SRR652248,SRR652249]
         foo: [ERR032203, ERR032204]

single_end: [SRR652248,SRR652249]
paired_end: [ERR032203,ERR032204]

mouse:
        runs: [SRR652248,SRR652249,ERR032203,ERR032204]

human:
        runs: []

mirnas: [mmu-miR-29b-3p,mmu-miR-132-3p, mmu-miR-7061-5p] #if this configuration is left blank - processing is performed for all miRNAs of a given species as default
transcripts: [ENSMUST00000055032.13]
